[[test_servers]]
name = "vm"
host = "192.168.2.232"
user = "vagrant"
key = "environments/cms/ssh_key/test_key"

[contest]
name = "test"
description = "Test"
token_mode = "infinite"

[[contest.users]]
username = "u1"
password = "p1"

[contest-config]
languages = ["C11 / gcc", "C++17 / g++", "Java / JDK", "Python 3 / CPython"]

[contest-config.mapping]
"C11 / gcc" = [".c"]
"C++17 / g++" = [".cpp", ".cc", ".cxx", ".c++", ".C"]
"Java / JDK" = [".java"]
"Python 3 / CPython" = [".py"]

[task_template]
infile = ""
outfile = ""
task_type = "Batch"
score_mode = "max_subtask" # 2017~
token_mode = "infinite"
score_type = "GroupMin"
score_type_parameters = ""
time_limit = 15
memory_limit = 1024

[[tasks]]
name = "agreement"
title = "agreement"
time_limit = 5.0
  [tasks.inclusive_tests]
  2 = ["1"]
  4 = ["1", "2", "3"]

[[tasks]]
name = "aisimulation"
title = "aisimulation"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]

[[tasks]]
name = "autocopilot"
title = "autocopilot"
time_limit = 1.5
  [tasks.inclusive_tests]
  2 = ["1"]
  4 = ["1", "2", "3"]

[[tasks]]
name = "convexhull"
title = "convexhull"
time_limit = 0.4
  [tasks.inclusive_tests]
  4 = ["1", "2", "3"]

[[tasks]]
name = "maze"
title = "maze"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]

[[tasks]]
name = "monster"
title = "monster"
time_limit = 1.0
  [tasks.inclusive_tests]
  3 = ["1"]
  5 = ["1", "2", "3", "4"]

[[tasks]]
name = "museum"
title = "museum"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]

[[tasks]]
name = "palindrome"
title = "palindrome"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]
  4 = ["1", "2", "3"]

[[tasks]]
name = "race"
title = "race"
time_limit = 2.0
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]
  5 = ["1", "2", "3", "4"]
